# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Hey-Cache
version:      0.01
version_from: lib/Hey/Cache.pm
installdirs:  site
requires:
    Data::DumpXML:                 1.01
    Data::DumpXML::Parser:         1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
